"""
codemind_okf/core/index_builder.py — OKF index.md Generator
=============================================================
Reads all .okf/modules/*.md files and builds the master index.md
with full YAML frontmatter so AI IDEs can read it as their primary context.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import frontmatter as fm

from codemind_okf.core.file_utils import safe_write


_EMOJI = {
    "module": "🔧",
    "architecture": "🏗️",
    "concept": "💡",
    "api": "🌐",
    "database": "🗄️",
    "config": "⚙️",
    "test": "🧪",
    "index": "📚",
    "changelog": "📜",
    "unknown": "📄",
}


def build_index(bundle_root: Path, project_name: str) -> Path:
    """
    Generate (or regenerate) the .okf/index.md for a bundle.
    Groups module files by their `type` field.
    """
    modules_dir = bundle_root / "modules"
    files = []

    if modules_dir.is_dir():
        for md_path in sorted(modules_dir.glob("*.md")):
            raw = md_path.read_text(encoding="utf-8", errors="replace")
            try:
                post = fm.loads(raw)
                meta = post.metadata
                files.append({
                    "filename": f"modules/{md_path.name}",
                    "title": str(meta.get("title", md_path.stem)),
                    "type": str(meta.get("type", "module")),
                    "description": meta.get("description", ""),
                    "tags": list(meta.get("tags", [])),
                    "resource": meta.get("resource", ""),
                })
            except Exception:
                continue

    # Group by type
    groups: dict[str, list] = {}
    for f in files:
        groups.setdefault(f["type"], []).append(f)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "---",
        "type: index",
        "title: Master Project Index",
        "description: Table of contents and navigation index for the entire repository bundle.",
        "tags:",
        "  - index",
        "  - overview",
        "---",
        "",
        f"# OKF Knowledge Bundle — `{project_name}`",
        "",
        f"> Generated by **CodeMind CLI** on {now}  ",
        f"> **{len(files)} modules** across **{len(groups)} architecture layers**  ",
        f"> _Use this index as your primary codebase context in any AI IDE._",
        "",
        "---",
        "",
    ]

    # Category navigation
    lines.append("## 📂 Architecture Layers")
    lines.append("")
    for type_name in sorted(groups.keys()):
        count = len(groups[type_name])
        emoji = _EMOJI.get(type_name.lower(), "📄")
        anchor = type_name.lower().replace(" ", "-")
        lines.append(f"- [{emoji} {type_name.title()}](#{anchor}) — {count} file(s)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Per-type sections
    for type_name in sorted(groups.keys()):
        type_files = groups[type_name]
        emoji = _EMOJI.get(type_name.lower(), "📄")
        lines.append(f"## {emoji} {type_name.title()}")
        lines.append("")

        for f in sorted(type_files, key=lambda x: x["title"]):
            link = f"[{f['title']}](./{f['filename']})"
            description = f["description"] or "_No description provided._"
            tags_str = " · ".join(f"`{t}`" for t in f["tags"][:4]) if f["tags"] else ""
            resource = f["resource"]

            lines.append(f"### {link}")
            lines.append(description)
            if resource:
                lines.append(f"**Source:** `{resource}`")
            if tags_str:
                lines.append(f"**Tags:** {tags_str}")
            lines.append("")

    lines += [
        "---",
        "",
        "_This index is automatically regenerated by `codemind index`._  ",
        "_See [log.md](./log.md) for change history._",
        "",
    ]

    content = "\n".join(lines)
    index_path = bundle_root / "index.md"
    safe_write(index_path, content)
    return index_path


def append_to_log(bundle_root: Path, message: str) -> None:
    """Append a timestamped entry to .okf/log.md."""
    log_path = bundle_root / "log.md"
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    entry = f"\n- `{timestamp}` — {message}"

    if log_path.exists():
        existing = log_path.read_text(encoding="utf-8")
        safe_write(log_path, existing + entry)
    else:
        header = (
            "---\ntype: changelog\ntitle: Bundle Audit Log\n"
            "description: Audit trail of bundle creation and updates.\ntags:\n  - log\n  - audit\n---\n\n"
            "# OKF Bundle Change Log\n\n_Auto-generated by CodeMind CLI._\n"
        )
        safe_write(log_path, header + entry)
